package backend.service;

import backend.models.Appointment;
import backend.models.CustomerFeedback;
import backend.models.ServicePrice;
import backend.models.User;
import backend.models.enums.AppointmentStatus;
import backend.models.enums.Role;
import backend.models.enums.ServiceType;
import backend.repository.AppointmentRepository;
import backend.repository.FeedbackRepository;
import backend.repository.ServicePriceRepository;
import backend.repository.UserRepository;
import backend.util.SessionManager;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.EnumMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

public class GenerateReportService {
    private final FeedbackRepository feedbackRepository;
    private final AppointmentRepository appointmentRepository;
    private final UserRepository userRepository;
    private final ServicePriceRepository servicePriceRepository;
    private final SessionManager sessionManager;

    public GenerateReportService(FeedbackRepository feedbackRepository, AppointmentRepository appointmentRepository, UserRepository userRepository, ServicePriceRepository servicePriceRepository, SessionManager sessionManager) {
        this.feedbackRepository = feedbackRepository;
        this.appointmentRepository = appointmentRepository;
        this.userRepository = userRepository;
        this.servicePriceRepository = servicePriceRepository;
        this.sessionManager = sessionManager;
    }


    public String generateReport(){
        List<User> users = userRepository.findAll();
        List<Appointment> appointments = appointmentRepository.findAll();
        List<CustomerFeedback> feedbacks = feedbackRepository.findAll();
        List<ServicePrice> servicePrices = servicePriceRepository.findAll();

        int managerCount = 0;
        int counterStaffCount = 0;
        int technicianCount = 0;
        int customerCount = 0;
        for (User user : users) {
            switch (user.getRole()) {
                case MANAGER -> managerCount++;
                case COUNTER_STAFF -> counterStaffCount++;
                case TECHNICIAN -> technicianCount++;
                case CUSTOMER -> customerCount++;
            }
        }

        Map<AppointmentStatus, Integer> appointmentStatusCounts = new EnumMap<>(AppointmentStatus.class);
        for (AppointmentStatus status : AppointmentStatus.values()) {
            appointmentStatusCounts.put(status, 0);
        }

        Map<String, TechnicianStats> technicianStats = new LinkedHashMap<>();
        for (User user : users) {
            if (user.getRole() == Role.TECHNICIAN) {
                technicianStats.put(user.getUserId(), new TechnicianStats(user.getUsername(), user.getUserId()));
            }
        }

        for (Appointment appointment : appointments) {
            appointmentStatusCounts.put(appointment.getStatus(), appointmentStatusCounts.get(appointment.getStatus()) + 1);
            if (appointment.getStatus() == AppointmentStatus.COMPLETED) {
                TechnicianStats stats = technicianStats.get(appointment.getTechnicianId());
                if (stats != null) {
                    stats.completedAppointments++;
                }
            }
        }

        for (CustomerFeedback feedback : feedbacks) {
            TechnicianStats stats = technicianStats.get(feedback.getTechnicianId());
            if (stats != null) {
                stats.feedbackCount++;
                stats.ratingTotal += feedback.getRating();
            }
        }

        Map<ServiceType, ServicePrice> latestPrices = new EnumMap<>(ServiceType.class);
        for (ServicePrice servicePrice : servicePrices) {
            latestPrices.put(servicePrice.getServiceType(), servicePrice);
        }

        User currentUser = sessionManager.getCurrentUser();
        String generatedBy = currentUser == null
                ? "System"
                : currentUser.getUsername() + " (" + currentUser.getUserId() + ")";

        StringBuilder report = new StringBuilder();
        report.append("===== MANAGER REPORT =====\n");
        report.append("Generated By: ").append(generatedBy).append("\n");
        report.append("Generated At: ").append(LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"))).append("\n\n");

        report.append("-- Registration Summary --\n");
        report.append("Managers Registered: ").append(managerCount).append("\n");
        report.append("Counter Staff Registered: ").append(counterStaffCount).append("\n");
        report.append("Technicians Registered: ").append(technicianCount).append("\n");
        report.append("Customers Registered: ").append(customerCount).append("\n");
        report.append("Total Staff Registered: ").append(managerCount + counterStaffCount + technicianCount).append("\n\n");

        report.append("-- Appointment Summary --\n");
        report.append("Total Appointments: ").append(appointments.size()).append("\n");
        report.append("Confirmed Appointments: ").append(appointmentStatusCounts.get(AppointmentStatus.CONFIRMED)).append("\n");
        report.append("Completed Appointments: ").append(appointmentStatusCounts.get(AppointmentStatus.COMPLETED)).append("\n");
        report.append("Cancelled Appointments: ").append(appointmentStatusCounts.get(AppointmentStatus.CANCELLED)).append("\n");
        report.append("Pending Appointments: ").append(appointmentStatusCounts.get(AppointmentStatus.PENDING)).append("\n");
        report.append("In Progress Appointments: ").append(appointmentStatusCounts.get(AppointmentStatus.IN_PROGRESS)).append("\n\n");

        report.append("-- Technician Performance --\n");
        if (technicianStats.isEmpty()) {
            report.append("No technicians registered.\n");
        } else {
            for (TechnicianStats stats : technicianStats.values()) {
                double averageRating = stats.feedbackCount == 0 ? 0.0 : (double) stats.ratingTotal / stats.feedbackCount;
                report.append(stats.username)
                        .append(" (").append(stats.userId).append(")")
                        .append(" - Completed Appointments: ").append(stats.completedAppointments)
                        .append(", Feedback: ").append(stats.feedbackCount)
                        .append(", Average Rating: ").append(String.format("%.2f", averageRating))
                        .append("\n");
            }
        }
        report.append("\n");

        report.append("-- Feedback Summary --\n");
        report.append("Total Feedback Entries: ").append(feedbacks.size()).append("\n");
        if (!feedbacks.isEmpty()) {
            int ratingTotal = 0;
            Map<Integer, Integer> ratingCounts = new LinkedHashMap<>();
            for (int rating = 1; rating <= 5; rating++) {
                ratingCounts.put(rating, 0);
            }
            for (CustomerFeedback feedback : feedbacks) {
                ratingTotal += feedback.getRating();
                ratingCounts.put(feedback.getRating(), ratingCounts.get(feedback.getRating()) + 1);
            }
            double averageRating = (double) ratingTotal / feedbacks.size();
            report.append("Average Rating: ").append(String.format("%.2f", averageRating)).append("\n");
            report.append("Rating Breakdown: ");
            boolean first = true;
            for (Map.Entry<Integer, Integer> entry : ratingCounts.entrySet()) {
                if (!first) {
                    report.append(", ");
                }
                report.append(entry.getKey()).append(" star=").append(entry.getValue());
                first = false;
            }
            report.append("\n");
        }
        report.append("\n");

        report.append("-- Service Price List --\n");
        if (latestPrices.isEmpty()) {
            report.append("No service prices available.\n");
        } else {
            for (ServiceType serviceType : ServiceType.values()) {
                ServicePrice servicePrice = latestPrices.get(serviceType);
                if (servicePrice != null) {
                    report.append(serviceType).append(" = ").append(servicePrice.getPrice()).append("\n");
                }
            }
        }

        report.append("========================\n");
        return report.toString();
    }

    private static class TechnicianStats {
        private final String username;
        private final String userId;
        private int completedAppointments;
        private int feedbackCount;
        private int ratingTotal;

        private TechnicianStats(String username, String userId) {
            this.username = username;
            this.userId = userId;
        }
    }
}
